### ISSUE TITLE
Report not Generating

### ISSUE THREAD

**Issue by uzairqidwai** [hrshadhin/school-management-system#1]
Hi,
I was testing your software and I found a bug. When i generate a report i get an error.
http://school.hrshadhin.me/gradesheet/print/170101/Final%20Exam/cl1
?

**Comment by hrshadhin** [comment]
Thanks for testing my application. I checked it. I think you did a mistake after you generate result you made a mark entry for Math subject. That's why generated result and entry marks not match and get array index. error. I will put a check and barrier for this type or mistake. Again thanks for report this issue.
